# Generated by Django 4.2.1 on 2024-05-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='imgage',
            new_name='image',
        ),
    ]
