# Generated by Django 4.2.1 on 2024-05-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_imgage_course_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
