# Generated by Django 4.2.1 on 2024-05-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
