# Generated by Django 4.2.1 on 2024-05-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcapacit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('id',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
    ]
