# Generated by Django 4.2.1 on 2024-05-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcapacit', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend')], default='backend', max_length=10)),
                ('description', models.TextField(default='programacion', max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'Profesor',
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default='sin clasificar', on_delete=django.db.models.deletion.CASCADE, to='appcapacit.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(default='sin asignacion', on_delete=django.db.models.deletion.CASCADE, to='appcapacit.tutor'),
        ),
    ]
